
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[214] =
    {   0,
       42,   42,    0,    0,    0,    0,    0,    0,   60,   58,
       44,   39,   39,   19,   45,   17,   58,   14,   23,    5,
        8,    2,    7,   58,    6,   42,   42,    1,   16,    4,
       11,   41,   15,   24,    3,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   12,
       58,   22,   50,   47,   47,   46,   49,   53,   52,   52,
       57,   56,   56,   57,   39,   18,   20,   40,   43,    0,
       54,   51,    0,   42,    0,   42,   13,    9,   10,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   40,   29,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   21,   49,   48,
       52,   56,   55,    0,   43,    0,   43,   42,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   28,   41,
       41,   41,   31,   40,    0,   41,   41,   41,   41,   41,
       41,   41,   30,   33,   41,   41,   41,   41,   41,   27,
       41,   41,    0,   37,   41,   41,    0,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,    0,
       41,   41,    0,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,    0,   41,    0,   41,   26,   41,
       34,   41,   41,   32,    0,   41,   38,   25,   41,   41,

        0,   41,    0,   41,    0,    0,   41,    0,    0,   35,
        0,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   20,   20,   20,   20,   20,   20,    1,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   31,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   30,   52,   53,   54,   55,   56,   57,   32,
       58,   30,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    1,    1,    1,    1,    4,    4,    4,    3,
        3,    3,    1,    1,    1,    3,    4,    4,    4,    4,
        4,    4,    4,    3,    4,    3,    3,    3,    3,    3,
        3,    3,    3,    4,    3,    3,    3,    3,    5,    1,
        5
    } ;

static const flex_int16_t yy_base[220] =
    {   0,
        0,    0,   59,   60,   66,   67,   70,   71,  204,  765,
      765,  765,  199,  176,  765,  765,  188,  765,  765,  765,
      181,  765,  176,   58,   68,   81,   87,  765,  164,  153,
      147,   69,  765,  765,   98,  104,  111,   97,   92,  115,
       77,  127,  100,  129,  130,  144,  146,  147,  149,  765,
      108,  765,  765,  765,  765,  765,   97,  765,  765,  157,
      765,  765,  155,  139,  765,  765,  765,  765,  187,  196,
      765,  765,  200,  206,  217,    0,  765,  765,  765,  205,
      206,  207,  217,  209,  226,  228,  229,  231,  243,  245,
      248,  257,  262,  260,  271,  276,  279,  280,  288,  297,

      300,  298,  309,  314,  317,  326,  328,  765,  765,  765,
      765,  765,  765,  362,  366,  370,  374,    0,  360,  361,
      362,  364,  365,  379,  380,  388,  389,  405,  390,  404,
      400,  408,  416,  419,  126,  424,  428,  436,  438,  448,
      440,  458,  439,  460,  463,  468,  479,  477,  489,  493,
      494,  503,  114,  505,  508,  517,   91,  522,  527,  526,
      536,  537,  545,  546,  554,  562,  563,  564,  580,   88,
      572,  581,   92,  584,  592,  595,  603,  600,  611,  614,
      619,  622,  623,  633,   70,  634,   59,  644,  642,  643,
      645,  659,  654,  664,   62,  668,  765,  669,  673,  678,

       43,  688,   69,  687,   48,   38,  690,   36,   32,  765,
       21,  765,  765,  740,  745,  750,  753,  757,  759
    } ;

static const flex_int16_t yy_def[220] =
    {   0,
      213,    1,  214,  214,  215,  215,  216,  216,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  217,  213,  213,  217,  217,  217,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,  213,
      213,  213,  213,  213,  213,  213,  218,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  219,  213,  213,  213,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   37,   37,   37,   37,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  219,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,  213,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,  213,   37,   37,   37,  213,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,  213,
       37,   37,  213,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,  213,   37,  213,   37,   37,   37,
       37,   37,   37,   37,  213,   37,  213,   37,   37,   37,

      213,   37,  213,   37,  213,  213,   37,  213,  213,  213,
      213,  213,    0,  213,  213,  213,  213,  213,  213
    } ;

static const flex_int16_t yy_nxt[827] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       27,   27,   28,   29,   30,   31,   32,   32,   32,   32,
       32,   32,   33,   10,   34,   35,   32,   36,   37,   38,
       39,   40,   41,   32,   42,   32,   32,   43,   32,   44,
       45,   46,   47,   48,   32,   49,   32,   32,   50,   51,
       52,   54,   54,   55,   55,  212,   56,   56,   59,   59,
       60,   60,   62,   62,   63,   63,   69,   69,   69,   69,
       71,  211,   64,   64,  210,   72,   70,   80,   80,   80,
       80,  209,   57,   57,  208,  206,  205,   73,   70,   74,

       74,   74,   74,   73,  110,   74,   74,   74,   74,   75,
      201,  197,   76,   81,  195,   75,   80,   80,   80,   80,
       81,   75,   80,   80,   80,   80,   94,   75,   81,   80,
       80,   80,   80,   81,  187,   81,   98,   87,   88,  185,
       81,   81,  173,   81,  170,  110,   81,   84,  110,   81,
      110,   89,  157,   82,   85,   83,  113,  112,   81,  111,
       86,   90,   91,   81,   92,   81,  100,  108,   95,   93,
       81,   79,   81,   81,   96,   97,   81,   78,   81,   81,
      101,   99,   81,   81,  102,  107,  103,   81,   77,   81,
       81,   68,   81,   81,   68,   81,   81,   67,   81,  104,

       66,   65,  105,  213,  106,   69,   69,   69,   69,  114,
      213,  114,  213,  213,  115,  115,  115,  115,   69,   69,
       69,   69,   73,  213,   74,   74,   74,   74,   70,  213,
      116,  213,  116,  213,   75,  117,  117,  117,  117,  213,
       70,   81,   81,   81,  213,   81,   75,  213,   81,   81,
       81,  213,   81,   81,   81,   81,  119,  120,   81,  213,
       81,  121,  122,  213,   81,   81,   81,   81,  213,   81,
      124,   81,   81,  213,   81,   81,  123,   81,   81,   81,
       81,   81,  213,  125,   81,  213,   81,  213,   81,  126,
      213,   81,   81,   81,  127,  213,   81,   81,   81,  213,

       81,  128,  213,   81,  135,   81,   81,   81,  129,   81,
      130,   81,   81,  131,   81,   81,   81,  213,  213,   81,
       81,  213,   81,   81,   81,   81,  132,  213,   81,   81,
      134,   81,  133,   81,   81,  136,   81,   81,  213,  213,
       81,   81,  213,   81,  213,   81,   81,   81,  137,   81,
       81,  138,   81,   81,  213,  139,  213,   81,   81,  213,
       81,  141,   81,   81,   81,  140,   81,  213,  213,   81,
      213,   81,  213,  213,  213,   81,  142,   81,  213,  143,
      115,  115,  115,  115,  115,  115,  115,  115,  117,  117,
      117,  117,  117,  117,  117,  117,   81,  145,   81,  213,

       81,   81,  134,   81,   81,   81,  144,   81,   81,   81,
       81,   81,  134,   81,   81,  148,   81,  146,  147,  149,
      150,  153,   81,   81,   81,  152,   81,  213,   81,   81,
      213,   81,   81,   81,  151,  213,   81,   81,   81,   81,
       81,   81,  154,   81,   81,  213,  213,   81,   81,  134,
      213,   81,   81,   81,   81,   81,  156,  155,  213,   81,
       81,  213,   81,  213,   81,   81,  213,   81,   81,  158,
      159,   81,   81,   81,   81,   81,   81,   81,  161,   81,
      213,   81,   81,   81,   81,   81,  162,   81,   81,   81,
      160,   81,  163,  165,   81,  213,   81,   81,  134,   81,

      213,   81,  164,   81,   81,  213,   81,   81,  134,   81,
      213,   81,   81,   81,  213,   81,  213,   81,  213,  213,
       81,  134,   81,  166,  213,   81,   81,  213,   81,   81,
       81,  167,   81,  213,  213,  213,   81,   81,   81,   81,
      134,   81,   81,   81,   81,  213,   81,  168,   81,  213,
      213,   81,   81,   81,   81,  213,  169,   81,  174,  171,
       81,  213,   81,   81,  213,   81,   81,  134,  172,   81,
       81,   81,   81,   81,  176,   81,   81,  175,  213,   81,
       81,   81,   81,  213,  179,   81,  177,  213,   81,   81,
       81,  213,  180,  178,   81,   81,  213,   81,   81,   81,

       81,  184,  213,   81,  213,   81,   81,  183,   81,  182,
      181,   81,   81,   81,  213,   81,   81,   81,  213,  213,
       81,   81,  186,   81,   81,  134,  188,   81,   81,   81,
       81,   81,  213,   81,  213,   81,   81,  213,   81,   81,
      189,   81,  191,   81,   81,  213,   81,   81,  134,   81,
       81,  190,   81,  194,   81,   81,  213,  134,   81,   81,
       81,  213,   81,   81,  134,   81,   81,  213,   81,   81,
      196,   81,   81,  192,  193,  134,   81,   81,   81,   81,
       81,   81,   81,   81,  198,   81,   81,   81,   81,  203,
       81,   81,   81,   81,   81,   81,  213,   81,  199,  134,

       81,  213,   81,  200,   81,   81,  202,   81,   81,   81,
      213,   81,   81,   81,   81,  213,   81,   81,   81,  213,
      213,   81,   81,   81,   81,  213,   81,   81,  134,  207,
       81,   81,  204,  134,  213,  213,   81,   81,  213,   81,
       53,   53,   53,   53,   53,   58,   58,   58,   58,   58,
       61,   61,   61,   61,   61,   81,   81,  109,  213,  109,
      109,  109,  118,  118,    9,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213
    } ;

static const flex_int16_t yy_chk[827] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,  211,    3,    4,    5,    6,
        5,    6,    7,    8,    7,    8,   24,   24,   24,   24,
       25,  209,    7,    8,  208,   25,   24,   32,   32,   32,
       32,  206,    3,    4,  205,  203,  201,   26,   24,   26,

       26,   26,   26,   27,   57,   27,   27,   27,   27,   26,
      195,  187,   26,   41,  185,   27,   35,   35,   35,   35,
       41,   26,   36,   36,   36,   36,   41,   27,   39,   37,
       37,   37,   37,   38,  173,   39,   43,   38,   39,  170,
       38,   39,  157,   43,  153,   57,   38,   37,   57,   43,
       57,   40,  135,   36,   37,   36,   64,   63,   40,   60,
       37,   40,   40,   42,   40,   44,   45,   51,   42,   40,
       42,   31,   44,   45,   42,   42,   42,   30,   44,   45,
       46,   44,   47,   48,   46,   49,   47,   46,   29,   47,
       48,   23,   49,   46,   21,   47,   48,   17,   49,   47,

       14,   13,   47,    9,   48,   69,   69,   69,   69,   70,
        0,   70,    0,    0,   70,   70,   70,   70,   73,   73,
       73,   73,   74,    0,   74,   74,   74,   74,   73,    0,
       75,    0,   75,    0,   74,   75,   75,   75,   75,    0,
       73,   80,   81,   82,    0,   84,   74,    0,   80,   81,
       82,    0,   84,   83,   80,   81,   82,   83,   84,    0,
       83,   84,   85,    0,   86,   87,   83,   88,    0,   85,
       87,   86,   87,    0,   88,   85,   86,   86,   87,   89,
       88,   90,    0,   88,   91,    0,   89,    0,   90,   89,
        0,   91,   89,   92,   90,    0,   94,   91,   93,    0,

       92,   91,    0,   94,   99,   93,   92,   95,   92,   94,
       93,   93,   96,   94,   95,   97,   98,    0,    0,   96,
       95,    0,   97,   98,   99,   96,   96,    0,   97,   98,
       98,   99,   97,  100,  102,  100,  101,   99,    0,    0,
      100,  102,    0,  101,    0,  103,  100,  102,  101,  101,
      104,  102,  103,  105,    0,  103,    0,  104,  103,    0,
      105,  105,  106,  104,  107,  104,  105,    0,    0,  106,
        0,  107,    0,    0,    0,  106,  106,  107,    0,  107,
      114,  114,  114,  114,  115,  115,  115,  115,  116,  116,
      116,  116,  117,  117,  117,  117,  119,  120,  121,    0,

      122,  123,  121,  119,  120,  121,  119,  122,  123,  119,
      120,  121,  122,  122,  123,  124,  125,  123,  123,  124,
      125,  128,  124,  125,  126,  127,  129,    0,  124,  125,
        0,  126,  127,  129,  126,    0,  131,  126,  127,  129,
      130,  128,  130,  131,  132,    0,    0,  130,  128,  131,
        0,  132,  133,  130,  128,  134,  133,  132,    0,  133,
      136,    0,  134,    0,  137,  133,    0,  136,  134,  136,
      137,  137,  138,  136,  139,  143,  141,  137,  139,  138,
        0,  139,  143,  141,  140,  138,  140,  139,  143,  141,
      138,  140,  140,  141,  142,    0,  144,  140,  142,  145,

        0,  142,  140,  144,  146,    0,  145,  142,  145,  144,
        0,  146,  145,  148,    0,  147,    0,  146,    0,    0,
      148,  146,  147,  147,    0,  149,  148,    0,  147,  150,
      151,  148,  149,    0,    0,    0,  150,  151,  149,  152,
      149,  154,  150,  151,  155,    0,  152,  151,  154,    0,
        0,  155,  152,  156,  154,    0,  152,  155,  158,  155,
      156,    0,  160,  159,    0,  158,  156,  159,  156,  160,
      159,  158,  161,  162,  161,  160,  159,  160,    0,  161,
      162,  163,  164,    0,  164,  161,  162,    0,  163,  164,
      165,    0,  165,  163,  163,  164,    0,  165,  166,  167,

      168,  169,    0,  165,    0,  166,  167,  168,  171,  167,
      166,  166,  167,  168,    0,  171,  169,  172,    0,    0,
      174,  171,  172,  169,  172,  171,  174,  174,  175,  169,
      172,  176,    0,  174,    0,  175,  178,    0,  176,  177,
      175,  175,  178,  178,  176,    0,  177,  179,  176,  178,
      180,  177,  177,  184,  179,  181,    0,  180,  182,  183,
      179,    0,  181,  180,  179,  182,  183,    0,  181,  184,
      186,  182,  183,  181,  183,  182,  184,  186,  189,  190,
      188,  191,  184,  186,  188,  189,  190,  188,  191,  199,
      193,  189,  190,  188,  191,  192,    0,  193,  190,  192,

      194,    0,  192,  193,  196,  198,  196,  194,  192,  199,
        0,  196,  198,  194,  200,    0,  199,  196,  198,    0,
        0,  200,  199,  204,  202,    0,  207,  200,  202,  204,
      204,  202,  200,  207,    0,    0,  204,  202,    0,  207,
      214,  214,  214,  214,  214,  215,  215,  215,  215,  215,
      216,  216,  216,  216,  216,  217,  217,  218,    0,  218,
      218,  218,  219,  219,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 2 "gocompiler.l"
	#include <stdlib.h>
	#include <stdio.h>
	#include <string.h>
	#include <stdarg.h>
	
	#define ERROR_GENERIC_MSG "Line %d, column %d: "
	#define BUF_SIZE 4096
	
	static int current_line = 1, current_column = 1, start = 0, str_error = 0, last_token = 0, comment_line = 0, comment_column = 0;
	static char buf[BUF_SIZE], buf_counter = 0;
	
	typedef enum {
		NEW_LINE,
		SEMICOLON,
		COMMA,
		BLANK_ID,
		ASSIGN,
		STAR,
		DIV,
		MINUS,
		PLUS,
		EQ,
		GE,
		GT,
		LBRACE,
		LE,
		LPAR,
		LSQ,
		LT,
		MOD,
		NE,
		NOT,
		AND,
		OR,
		RBRACE,
		RPAR,
		RSQ,
		PACKAGE,
		RETURN,
		ELSE,
		FOR,
		IF,
		VAR,
		INT,
		FLOAT32,
		BOOL,
		STRING,
		PRINT,
		PARSE_INT,
		FUNC,
		CMDARGS,
		RESERVED,
		ID,
		INT_LIT,
		REAL_LIT,
		STRING_LIT,
		OTHER,
		STRING_START,
		STRING_END,
		LINE_COMMENT_START,
		GENERAL_COMMENT_START,
		GENERAL_COMMENT_END,
		IGNORE,
		IGNORE_NEW_LINE
	} token_type;
		
	typedef enum {
		ILLEGAL_CHAR,
		UNTERMINATED_COMMENT,
		INVALID_OCTAL_CONST,
		UNTERMINATED_STR_LIT,
		INVALID_ESCAPE_SEQ
	} error_type;
	
	const char * token_types[] = {
		"NEW_LINE",
		"SEMICOLON",	
		"COMMA",
		"BLANKID",
		"ASSIGN",
		"STAR",
		"DIV",
		"MINUS",
		"PLUS",
		"EQ",
		"GE",
		"GT",
		"LBRACE",
		"LE",
		"LPAR",
		"LSQ",
		"LT",
		"MOD",
		"NE",
		"NOT",
		"AND",
		"OR",
		"RBRACE",
		"RPAR",
		"RSQ",
		"PACKAGE",
		"RETURN",
		"ELSE",
		"FOR",
		"IF",
		"VAR",
		"INT",
		"FLOAT32",
		"BOOL",
		"STRING",
		"PRINT",
		"PARSEINT",
		"FUNC",
		"CMDARGS",
		"RESERVED",
		"ID",
		"INTLIT",
		"REALLIT",
		"STRLIT",
		"OTHER",
		"STRING_START",
		"STRING_END",
		"LINE_COMMENT_START",
		"GENERAL_COMMENT_START",
		"GENERAL_COMMENT_END",
		"IGNORE",
		"IGNORE_NEW_LINE"
	};
	
	const char * error_msgs[] = {
		"illegal character (%s)",
		"unterminated comment",
		"invalid octal constant (%s)",
		"unterminated string literal",
		"invalid escape sequence (%s)"
	};
	
	static void handle_token(token_type type);
	static void lex_error(error_type err_type, int curr_column);

#line 837 "lex.yy.c"

#line 839 "lex.yy.c"

#define INITIAL 0
#define STATE_STRING 1
#define STATE_LINE_COMMENT 2
#define STATE_GENERAL_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 196 "gocompiler.l"


#line 1062 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 214 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 765 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 198 "gocompiler.l"
{handle_token(SEMICOLON);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 199 "gocompiler.l"
{handle_token(COMMA);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 200 "gocompiler.l"
{handle_token(BLANK_ID);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 201 "gocompiler.l"
{handle_token(ASSIGN);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 202 "gocompiler.l"
{handle_token(STAR);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 203 "gocompiler.l"
{handle_token(DIV);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 204 "gocompiler.l"
{handle_token(MINUS);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 205 "gocompiler.l"
{handle_token(PLUS);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 206 "gocompiler.l"
{handle_token(EQ);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 207 "gocompiler.l"
{handle_token(GE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 208 "gocompiler.l"
{handle_token(GT);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 209 "gocompiler.l"
{handle_token(LBRACE);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 210 "gocompiler.l"
{handle_token(LE);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 211 "gocompiler.l"
{handle_token(LPAR);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 212 "gocompiler.l"
{handle_token(LSQ);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 213 "gocompiler.l"
{handle_token(LT);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 214 "gocompiler.l"
{handle_token(MOD);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 215 "gocompiler.l"
{handle_token(NE);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 216 "gocompiler.l"
{handle_token(NOT);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 217 "gocompiler.l"
{handle_token(AND);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 218 "gocompiler.l"
{handle_token(OR);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 219 "gocompiler.l"
{handle_token(RBRACE);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 220 "gocompiler.l"
{handle_token(RPAR);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 221 "gocompiler.l"
{handle_token(RSQ);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 223 "gocompiler.l"
{handle_token(PACKAGE);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 224 "gocompiler.l"
{handle_token(RETURN);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 225 "gocompiler.l"
{handle_token(ELSE);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 226 "gocompiler.l"
{handle_token(FOR);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 227 "gocompiler.l"
{handle_token(IF);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 228 "gocompiler.l"
{handle_token(VAR);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 229 "gocompiler.l"
{handle_token(INT);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 230 "gocompiler.l"
{handle_token(FLOAT32);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 231 "gocompiler.l"
{handle_token(BOOL);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 232 "gocompiler.l"
{handle_token(STRING);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 233 "gocompiler.l"
{handle_token(PRINT);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 234 "gocompiler.l"
{handle_token(PARSE_INT);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 235 "gocompiler.l"
{handle_token(FUNC);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 236 "gocompiler.l"
{handle_token(CMDARGS);}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 238 "gocompiler.l"
{handle_token(NEW_LINE);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 239 "gocompiler.l"
{handle_token(RESERVED);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 240 "gocompiler.l"
{handle_token(ID);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 241 "gocompiler.l"
{handle_token(INT_LIT);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 242 "gocompiler.l"
{handle_token(REAL_LIT);}
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 243 "gocompiler.l"
{;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 245 "gocompiler.l"
{buf[0] = '\0'; buf_counter = 0; str_error = 0; start = current_column; BEGIN STATE_STRING;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 246 "gocompiler.l"
{BEGIN 0; if (!str_error) handle_token(STRING_LIT);}
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 247 "gocompiler.l"
{BEGIN 0; lex_error(UNTERMINATED_STR_LIT, start); current_line++; current_column = 1;}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 248 "gocompiler.l"
{BEGIN 0; lex_error(UNTERMINATED_STR_LIT, start); current_line++; current_column = 1;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 249 "gocompiler.l"
{current_column += 2;buf[buf_counter++] = yytext[0];buf[buf_counter++] = yytext[1];}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 250 "gocompiler.l"
{lex_error(INVALID_ESCAPE_SEQ, current_column + 1);current_column+=strlen(yytext); str_error = 1;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 251 "gocompiler.l"
{current_column++;buf[buf_counter++] = yytext[0];}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 253 "gocompiler.l"
{BEGIN STATE_LINE_COMMENT;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 254 "gocompiler.l"
{handle_token(IGNORE_NEW_LINE); BEGIN 0;}						
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 255 "gocompiler.l"
{handle_token(IGNORE);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 257 "gocompiler.l"
{BEGIN STATE_GENERAL_COMMENT; comment_line = current_line; comment_column = current_column;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 258 "gocompiler.l"
{BEGIN 0;}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 259 "gocompiler.l"
{handle_token(IGNORE_NEW_LINE);}
	YY_BREAK
case YY_STATE_EOF(STATE_GENERAL_COMMENT):
#line 260 "gocompiler.l"
{current_line = comment_line; current_column = comment_column; lex_error(UNTERMINATED_COMMENT, current_column); exit(EXIT_FAILURE);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 261 "gocompiler.l"
{handle_token(IGNORE);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 263 "gocompiler.l"
{lex_error(ILLEGAL_CHAR, current_column+=strlen(yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 266 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1427 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 214 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 214 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 213);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 266 "gocompiler.l"


int main(int argc, char * argv[]) {
	yylex();
	
	return EXIT_SUCCESS;
}

int yywrap() {

	return 1;
}

void handle_token(token_type tok_type) {
	char * tok = yytext;
	current_column += strlen(tok);
	
	switch (tok_type) {
		case ID:
		case INT_LIT:
		case REAL_LIT:
		case RESERVED:
			printf("%s(%s)\n", token_types[tok_type], tok);
			break;
		case STRING_LIT:
			buf[buf_counter] = '\0'; 
			printf("%s(\"%s\")\n", token_types[STRING_LIT], buf);
			buf[0] = '\0'; 
			buf_counter = 0;
			break;
		case NEW_LINE:
		case IGNORE_NEW_LINE:
			current_line++;
			current_column = 1;

			switch(last_token) {
				case INT_LIT:
				case REAL_LIT:
				case STRING_LIT:
				case ID:
				case RETURN:
				case RPAR:
				case RSQ:
				case RBRACE:
					handle_token(SEMICOLON);
					break;
				default:
					break;
			}

			break;
		case IGNORE:
			break;
		default:
			printf("%s\n", token_types[tok_type]);	
	}
	last_token = tok_type;
}

void lex_error_inner(error_type err_type, int curr_column, ...) {
	va_list args;
   
   	va_start(args, curr_column);
	char buffer[BUF_SIZE], buffer2[BUF_SIZE];
	snprintf(buffer, BUF_SIZE, ERROR_GENERIC_MSG, current_line, curr_column);
	vsnprintf(buffer2, BUF_SIZE, error_msgs[err_type], args);
	
	printf("%s%s\n", buffer, buffer2);
	
   	va_end(args);
}

void lex_error(error_type err_type, int curr_column) {
	lex_error_inner(err_type, curr_column, yytext);
}
